# Generated by Django 5.0.1 on 2025-03-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.IntegerField(default='0', null=True)),
            ],
        ),
    ]
